using FastTransforms, LinearAlgebra, Test

include("specialfunctionstests.jl")
include("chebyshevtests.jl")
include("quadraturetests.jl")
include("libfasttransformstests.jl")
include("nuffttests.jl")
include("paduatests.jl")
include("gaunttests.jl")
include("hermitetests.jl")
include("toeplitzplanstests.jl")
include("toeplitzhankeltests.jl")
include("toeplitzplushankeltests.jl")
include("grammatrixtests.jl")
include("bivariategrammatrixtests.jl")
include("arraystests.jl")
